package constant

var (
	LOYALTYBRANCHCODE = `9790`

	EARNREPORTCODE       = `MLWEARN001`
	DMREARNDAILY         = `D`
	LOYALTYEARNINGREPORT = LOYALTYBRANCHCODE + `_` + EARNREPORTCODE + `_` + DMREARNDAILY + `_{DDMMYYYY}`

	REDEEMREPORTCODE    = `MLWREDEEM001`
	DMRREDEEMDAILY      = `D`
	LOYALTYREDEEMREPORT = LOYALTYBRANCHCODE + `_` + REDEEMREPORTCODE + `_` + DMRREDEEMDAILY + `_{DDMMYYYY}`

	LOYALTYRECONFILE      = `LW_RECON_{YYYYMMDD}`
	LOYALTYREPORTFILETYPE = `.CSV`

	LOYALTYPOINTCLEARING = `LW_POINTCLEARING_{YYYYMMDD}.txt`
)
